language: python
python:
  - 3.5
install:
  - pip install -r requirements.txt
script: 
  - make -C docs/ html
  - touch docs/_build/html/.nojekyll
deploy:
  - provider: pages:git
    verbose: true
    token: $GITHUB_TOKEN
    edge: true
    local_dir: ./docs/_build/html/
    keep_history: true