language: python
python:
  - 3.5
install:
  - pip install sphinx sphinx_rtd_theme nbsphinx recommonmark
script: 
  - make -C docs/ html
  - touch docs/build/html/.nojekyll
deploy:
  - provider: pages:git
    verbose: true
    token: $GITHUB_TOKEN
    edge: true
    local_dir: ./docs/build/html/
    keep_history: true