# This is a basic workflow to help you get started with Actions

name: docs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Checkout ibllib repo
        uses: actions/checkout@v2
        with:
          repository: int-brain-lab/ibllib
          path: ibllib-repo
        
      - name: Move ibllib
        run: |
          mv ibllib-repo ../
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: Install docs requirements
        run: |
          sudo apt install pandoc
          cd docs_gh_pages
          pip install -r requirements-docs.txt
          jupyter nbextension enable --py --sys-prefix ipyevents
      
      - name: Install ibllib
        run: |
          cd ../ibllib-repo
          pip install -r requirements.txt
          pip install -e.

      - name: build docs
        run: |
          cd docs/
          python ./make_script.py -d

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
